server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://distributor:8001/loki/api/v1/push
    tenant_id: cerebral

scrape_configs:
  - job_name: host
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
          target_label: hostname
