version: "3.4"
services:
  consul:
    logging: &logging
      driver: loki-compose
      options:
        loki-url: "${LOGS_URL}"
        loki-retries: "1"
    image: consul
    command: ["agent", "-dev", "-client=0.0.0.0", "-log-level=info"]
    ports:
      - 8500:8500

  minio:
    logging:
      <<: *logging
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/loki && /opt/bin/minio server /data'
    environment:
      - MINIO_ACCESS_KEY=loki
      - MINIO_SECRET_KEY=supersecret
    ports:
      - 9000:9000
    volumes:
      - ./.data/minio:/data:delegated

  memcached:
    logging:
      <<: *logging
    image: memcached:1.6

  jaeger:
    logging:
      <<: *logging
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - "14268"

  distributor:
    logging:
      <<: *logging
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    command:
      [
        "sh",
        "-c",
        "sleep 3 && exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- -config.file=./config/loki.yaml -target=distributor",
      ]
    depends_on:
      - ingester
      - consul
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=distributor
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3100
      - 9095
      - 18001
    volumes:
      - ./config:/loki/config
    networks:
      default:
        aliases:
          - loki

  ingester:
    logging:
      <<: *logging
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    command:
      [
        "sh",
        "-c",
        "sleep 3 && exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- -config.file=./config/loki.yaml -target=ingester",
      ]
    depends_on:
      - consul
      - minio
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=ingester
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3100
      - 9095
      - 18001
    volumes:
      - ./config:/loki/config
      - ./.data/ingester:/data:delegated
    networks:
      default:
        aliases:
          - loki

  querier:
    logging:
      <<: *logging
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    command:
      [
        "sh",
        "-c",
        # "sleep 3 && exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- -config.file=./config/loki.yaml -target=querier -querier.scheduler-address=query-scheduler:9095",
        "./loki -config.file=./config/loki.yaml -target=querier -querier.scheduler-address=query-scheduler:9095",
      ]
    depends_on:
      - consul
      - minio
      - query-frontend
      - query-scheduler
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=querier
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - 3100
      - 9095
      - 18001
    volumes:
      - ./config:/loki/config
      - ./.data/querier:/data:delegated
    networks:
      default:
        aliases:
          - loki

  index-gateway:
    logging:
      <<: *logging
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    command:
      [
        "sh",
        "-c",
        "sleep 3 && exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- -config.file=./config/loki.yaml -target=index-gateway -boltdb.shipper.query-ready-num-days=30",
      ]
    depends_on:
      - consul
      - minio
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=index-gateway
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3100
      - 9095
      - 18001
    volumes:
      - ./config:/loki/config
    networks:
      default:
        aliases:
          - loki

  compactor:
    logging:
      <<: *logging
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    command:
      [
        "sh",
        "-c",
        "sleep 3 && exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- -config.file=./config/loki.yaml -target=compactor -server.http-listen-port=8006 -server.grpc-listen-port=9006",
      ]
    depends_on:
      - consul
      - minio
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=compactor
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3100
      - 9095
      - 18001
    volumes:
      - ./config:/loki/config
      - ./.data/compactor:/data:delegated
    networks:
      default:
        aliases:
          - loki

  query-frontend:
    logging:
      <<: *logging
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    command:
      [
        "sh",
        "-c",
        # "sleep 3 && exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- -config.file=./config/loki.yaml -target=query-frontend -frontend.scheduler-address=query-scheduler:9095",
        "./loki -config.file=./config/loki.yaml -target=query-frontend -frontend.scheduler-address=query-scheduler:9095",
      ]
    depends_on:
      - consul
      - minio
      - query-scheduler
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=query-frontend
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3100
      - 9095
      - 18001
    volumes:
      - ./config:/loki/config
    networks:
      default:
        aliases:
          - loki

  query-scheduler:
    logging:
      <<: *logging
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    command:
      [
        "sh",
        "-c",
        "sleep 3 && exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- -config.file=./config/loki.yaml -target=query-scheduler",
      ]
    depends_on:
      - consul
      - minio
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=query-scheduler
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 3100
      - 9095
      - 18001
    volumes:
      - ./config:/loki/config
    networks:
      default:
        aliases:
          - loki

  grafana:
    logging:
      <<: *logging
    image: grafana/grafana
    depends_on:
      - query-frontend
      - querier
    environment:
      - GF_PATHS_PROVISIONING=/etc/config/grafana/provisioning
    ports:
      - 3000:3000
    volumes:
      - ./config/datasource.yaml:/etc/config/grafana/provisioning/datasources/ds.yaml

  # log-gen:
  #   logging:
  #     <<: *logging
  #   image: mingrammer/flog
  #   command: ["-f", "json", "-l", "-s", "1s"]
  #   depends_on:
  #     - distributor

  promtail:
    logging:
      <<: *logging
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
      - ./config:/config
    command: -config.file=/config/promtail.yaml
    depends_on:
      - distributor
