#!/usr/bin/env bash

address="https://logs-prod-us-central1.grafana.net"

set +e
op list items 2>&1 > /dev/null
if [[ $? -ne 0 ]]; then
  eval "$(op signin my)"
fi
set -e
grafana_com_logs=$(op get item grafana-com-logs | jq '.details.sections | .[].fields')
logs_hostname=$(echo "$grafana_com_logs" | jq -r '.[] | select(.t == "hostname") | .v')
logs_user=$(echo "$grafana_com_logs" | jq -r '.[] | select(.t == "username") | .v')
logs_token=$(echo "$grafana_com_logs" | jq -r '.[] | select(.t == "viewer-key") | .v')

fifteen_minutes_ago="$(date --date="@$(qalc -t "$(date -u "+%s") - 900")" +%Y-%m-%dT%H:%M:%SZ)"
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

project="${1}"; shift
component="${1}"; shift
if [[ "$#" -eq 0 ]]; then
  query="{compose_project=\"$project\", compose_service=\"$component\"}"
else
  query="{compose_project=\"$project\", compose_service=\"$component\"} ${@}"
fi

echo "Query: $query"

logcli query \
  --tail \
  --quiet \
  --addr="https://${logs_hostname}" \
  --username="${logs_user}" \
  --password="${logs_token}" \
  --since 15m \
  "${query}"
