{{- if not .Values.useExternalConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-logs-config
  labels:
    {{- include "enterprise-logs.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl (toYaml .Values.config) . | b64enc }}
{{- end }}
