auth:
  type: enterprise

server:
  http_listen_port: 3100

cluster_name: enterprise-logs-test-fixture

license:
  path: /config/license.jwt

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/boltdb-shipper-active
    cache_location: /data/boltdb-shipper-cache
    shared_store: s3
  aws:
    endpoint: minio:9000
    insecure: true
    bucketnames: loki-data
    access_key_id: loki
    secret_access_key: supersecret

ruler:
  storage:
    type: local
    local:
      directory: /data/rules
  rule_path: /data/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory

compactor:
  working_directory: /data/compactor1
  shared_store: s3

admin_client:
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucket_name: loki-admin
      access_key_id: loki
      secret_access_key: supersecret
    type: s3
