---
version: '3.8'

services:
  loki:
    image: grafana/loki:listen-on-all-addresses-b26b73d-WIP
    ports:
      - 3100:3100
      - 9095
    entrypoint:
      - ""
    command:
      - sh
      - -euc
      - |
        cat /etc/loki/local-config.yaml >&2
        ip addr
        ifconfig

        /usr/bin/loki \
          -log.level=debug \
          -config.file=/etc/loki/local-config.yaml
    deploy:
      mode: replicated
      replicas: 1

  grafana:
    logging: &logging
      driver: loki-compose
      options:
        loki-url: "http://localhost:3100/write/loki/api/v1/push"
        loki-retries: "1"
        loki-tenant-id: "twhitney"
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/config/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - ./config/datasource.yaml:/etc/config/grafana/provisioning/datasources/ds.yaml

  # log-gen:
  #   logging:
  #     <<: *logging
  #   image: mingrammer/flog
  #   command: ["-f", "json", "-l", "-s", "5s"]
