auth_enabled: false

server:
  http_listen_port: 3100
  log_level: debug

memberlist:
  join_members:
    - read:7946
    - write:7946

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/boltdb-shipper-active
    cache_location: /data/boltdb-shipper-cache
    shared_store: s3
  aws:
    endpoint: minio:9000
    insecure: true
    bucketnames: loki-data
    access_key_id: loki
    secret_access_key: supersecret

ruler:
  storage:
    type: local
    local:
      directory: /data/rules
  rule_path: /data/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

compactor:
  working_directory: /data/compactor
  shared_store: s3

limits_config:
  ingestion_burst_size_mb: 200
  ingestion_rate_mb: 150

ingester:
  wal:
    enabled: true
    dir: /data/ingester/wal
  lifecycler:
    final_sleep: 0s
  max_transfer_retries: 0 # Chunk transfers disabled
