server:
  http_listen_port: 3100
  log_level: debug
memberlist:
  join_members:
    - loki:7946
schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /data
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
ruler:
  storage:
    s3:
      bucketnames: loki-ruler

#TODO: use "current" schema config for storage config and compactor
# storage_config:
#   boltdb_shipper:
#     active_index_directory: /data/boltdb-shipper-active
#     cache_location: /data/boltdb-shipper-cache
#     shared_store: s3
#   aws:
#     endpoint: minio:9000
#     insecure: true
#     bucketnames: loki-data
#     access_key_id: loki
#     secret_access_key: supersecret

