apiVersion: 1
datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
  - name: Enterprise Metrics (Team A)
    type: prometheus
    access: proxy
    url: http://gateway:3100/prometheus
    basicAuth: true
    basicAuthUser: team-a
    secureJsonData:
      basicAuthPassword: $TEAM_A_TOKEN
  - name: Enterprise Metrics (Team B)
    type: prometheus
    access: proxy
    url: http://gateway:3100/prometheus
    basicAuth: true
    basicAuthUser: team-b
    secureJsonData:
      basicAuthPassword: $TEAM_B_TOKEN
