---
version: "3.4"
services:
  # --- start loki section ---
  loki:
    image: grafana/loki:main-b26b73d-WIP
    entrypoint: ""
    command:
      - /bin/sh
      - -euc
      - |
        ip addr
        ifconfig

        /usr/bin/loki \
          -memberlist.join=loki:7946 \
          -ring.store=memberlist \
          -distributor.replication-factor=3 \
          -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100
      - 9095
    deploy: &replicated
      mode: replicated
      replicas: 3
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=read
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    networks: &loki-dns
      default:
        aliases:
          - loki

  gateway:
    image: nginx:latest
    volumes:
      - ./config:/etc/nginx:ro
    depends_on:
      - loki
    ports:
      - "3101:3101"

  # --- end loki section ---
  log-gen:
    logging: &logging
      driver: loki-compose
      options:
        loki-url: "http://localhost:3101/loki/api/v1/push"
        loki-retries: "1"
        loki-tenant-id: "twhitney"
    image: mingrammer/flog
    command: ["-f", "json", "-l", "-s", "5s"]
    depends_on:
      - gateway

  jaeger:
    logging:
      <<: *logging
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - "14268"

  grafana:
    logging:
      <<: *logging
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/config/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - ./config/datasource.yaml:/etc/config/grafana/provisioning/datasources/ds.yaml
    depends_on:
      - loki
