---
version: "3.4"
services:
  # --- start loki section ---
  read:
    logging: &logging
      driver: loki-compose
      options:
        loki-url: "${LOGS_URL}"
        loki-retries: "1"
    build:
      context: .
      dockerfile: dev.dockerfile
    image: loki
    ports:
      - 3100
      - 7946
      - 9095
      - 18001
    deploy: &replicated
      mode: replicated
      replicas: 2
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=read
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    command:
      - sh
      - -euc
      - |
        echo -n "waiting for minio to be ready: " >&2
        until wget -O /dev/null -S http://minio:9000/minio/health/ready 2>&1 | grep "200 OK" > /dev/null 2> /dev/null; do
          echo -n "." >&2
          sleep 2
        done
        echo " ready" >&2

        exec ./dlv exec ./loki --listen=:18001 --headless=true --api-version=2 --accept-multiclient --continue -- \
          -config.file=/config/config.yaml -s3.force-path-style -target=read
    volumes:
      - ./.data/read:/data:rw
      - ./config:/config
    networks: &loki-dns
      default:
        aliases:
          - loki

  write:
    logging:
      <<: *logging
    image: loki
    ports:
      - 3100
      - 7946
      - 9095
      - 18002
    deploy:
      <<: *replicated
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=write
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    command:
      - sh
      - -euc
      - |
        echo -n "waiting for minio to be ready: " >&2
        until wget -O /dev/null -S http://minio:9000/minio/health/ready 2>&1 | grep "200 OK" > /dev/null 2> /dev/null; do
          echo -n "." >&2
          sleep 2
        done
        echo " ready" >&2

        exec ./dlv exec ./loki --listen=:18002 --headless=true --api-version=2 --accept-multiclient --continue -- \
          -config.file=/config/config.yaml -s3.force-path-style -target=write
    volumes:
      - ./.data/write:/data:rw
      - ./config:/config
    networks:
      <<: *loki-dns

  compactor:
    logging:
      <<: *logging
    image: loki
    ports:
      - 3100
      - 7946
      - 9095
      - 18003
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_TAGS=app=compactor
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    command:
      - sh
      - -euc
      - |
        echo -n "waiting for minio to be ready: " >&2
        until wget -O /dev/null -S http://minio:9000/minio/health/ready 2>&1 | grep "200 OK" > /dev/null 2> /dev/null; do
          echo -n "." >&2
          sleep 2
        done
        echo " ready" >&2

        exec ./dlv exec ./loki --listen=:18003 --headless=true --api-version=2 --accept-multiclient --continue -- \
          -config.file=/config/config.yaml -s3.force-path-style -target=compactor
    volumes:
      - ./.data/compactor:/data:rw
      - ./config:/config
    networks:
      <<: *loki-dns

  gateway:
    logging:
      <<: *logging
    image: nginx:latest
    volumes:
      - ./config:/etc/nginx:ro
    depends_on:
      - read
      - write
    ports:
      - "3101:3101"

  # --- end loki section ---

  minio:
    logging:
      <<: *logging
    image: minio/minio:RELEASE.2021-01-16T02-19-44Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && mkdir -p /data/loki-admin && mkdir -p /data/loki-ruler && /usr/bin/minio server /data
    environment:
      - MINIO_ACCESS_KEY=loki
      - MINIO_SECRET_KEY=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000
    volumes:
      - ./.data/minio:/data

  jaeger:
    logging:
      <<: *logging
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - "14268"

  grafana:
    logging:
      <<: *logging
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/config/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - ./config/datasource.yaml:/etc/config/grafana/provisioning/datasources/ds.yaml

  log-gen:
    logging:
      driver: loki-compose
      options:
        loki-url: "http://localhost:3101/write/loki/api/v1/push"
        loki-retries: "1"
        loki-tenant-id: "twhitney"
    image: mingrammer/flog
    command: ["-f", "json", "-l", "-s", "5s"]
    depends_on:
      - gateway
