---
serviceMonitor:
  enabled: true
  labels:
    release: 'prometheus'
loki:
  config: |
    auth_enabled: false

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    server:
      http_listen_port: 3100

    common:
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          endpoint: minio.k3d-loki-migration-test.svc.cluster.local:9000
          bucketnames: loki-data
          secret_access_key: supersecret
          access_key_id: loki
          s3forcepathstyle: true
          insecure: true

    ingester:
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m

    schema_config:
      configs:
        - from: 2022-01-11
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

    {{- if .Values.indexGateway.enabled}}
    storage_config:
      boltdb_shipper:
        index_gateway_client: {{ dict "server_address" (printf "dns:///%s:9095" (include "loki.indexGatewayFullname" .)) }}
    {{- end}}

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100

    ruler:
      storage:
        s3:
          bucketnames: loki-rules

ingester:
  replicas: 3
  extraArgs:
    - '-ingester.flush-on-shutdown=true' 
    - '-log.level=debug'
querier:
  replicas: 3
